generator:
  class: sfPropelGenerator
  param:
    model_class:           Cre8MenuContent
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cre8_menu_content
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:              [=name, is_active, is_hidden]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
