<?php


/**
 * This class adds structure of 'cre8_menu_content_type_flash' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 21 14:34:19 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.cre8MenuPlugin.lib.model.map
 */
class Cre8MenuContentTypeFlashMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.cre8MenuPlugin.lib.model.map.Cre8MenuContentTypeFlashMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Cre8MenuContentTypeFlashPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Cre8MenuContentTypeFlashPeer::TABLE_NAME);
		$tMap->setPhpName('Cre8MenuContentTypeFlash');
		$tMap->setClassname('Cre8MenuContentTypeFlash');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('CRE8_MENU_CONTENT_ID', 'Cre8MenuContentId', 'INTEGER', 'cre8_menu_content', 'ID', true, null);

		$tMap->addColumn('FILE_NAME', 'FileName', 'VARCHAR', true, 128);

	} // doBuild()

} // Cre8MenuContentTypeFlashMapBuilder
