<?php

/**
 * Base static class for performing query and update operations on the 'cre8_menu_content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 04:40:01 2009
 *
 * @package    plugins.cre8MenuPlugin.lib.model.om
 */
abstract class BaseCre8MenuContentPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cre8_menu_content';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.cre8MenuPlugin.lib.model.Cre8MenuContent';

	/** The total number of columns. */
	const NUM_COLUMNS = 12;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'cre8_menu_content.ID';

	/** the column name for the CRE8_MENU_TYPE_ID field */
	const CRE8_MENU_TYPE_ID = 'cre8_menu_content.CRE8_MENU_TYPE_ID';

	/** the column name for the NAME field */
	const NAME = 'cre8_menu_content.NAME';

	/** the column name for the CRE8_CONTENT_TYPE_ID field */
	const CRE8_CONTENT_TYPE_ID = 'cre8_menu_content.CRE8_CONTENT_TYPE_ID';

	/** the column name for the SLUG field */
	const SLUG = 'cre8_menu_content.SLUG';

	/** the column name for the META_TITLE field */
	const META_TITLE = 'cre8_menu_content.META_TITLE';

	/** the column name for the META_DESCRIPTION field */
	const META_DESCRIPTION = 'cre8_menu_content.META_DESCRIPTION';

	/** the column name for the META_KEYWORDS field */
	const META_KEYWORDS = 'cre8_menu_content.META_KEYWORDS';

	/** the column name for the TEMPLATE field */
	const TEMPLATE = 'cre8_menu_content.TEMPLATE';

	/** the column name for the IS_ACTIVE field */
	const IS_ACTIVE = 'cre8_menu_content.IS_ACTIVE';

	/** the column name for the IS_HIDDEN field */
	const IS_HIDDEN = 'cre8_menu_content.IS_HIDDEN';

	/** the column name for the RANK field */
	const RANK = 'cre8_menu_content.RANK';

	/**
	 * An identiy map to hold any loaded instances of Cre8MenuContent objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Cre8MenuContent[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Cre8MenuTypeId', 'Name', 'Cre8ContentTypeId', 'Slug', 'MetaTitle', 'MetaDescription', 'MetaKeywords', 'Template', 'IsActive', 'IsHidden', 'Rank', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'cre8MenuTypeId', 'name', 'cre8ContentTypeId', 'slug', 'metaTitle', 'metaDescription', 'metaKeywords', 'template', 'isActive', 'isHidden', 'rank', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::CRE8_MENU_TYPE_ID, self::NAME, self::CRE8_CONTENT_TYPE_ID, self::SLUG, self::META_TITLE, self::META_DESCRIPTION, self::META_KEYWORDS, self::TEMPLATE, self::IS_ACTIVE, self::IS_HIDDEN, self::RANK, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'cre8_menu_type_id', 'name', 'cre8_content_type_id', 'slug', 'meta_title', 'meta_description', 'meta_keywords', 'template', 'is_active', 'is_hidden', 'rank', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Cre8MenuTypeId' => 1, 'Name' => 2, 'Cre8ContentTypeId' => 3, 'Slug' => 4, 'MetaTitle' => 5, 'MetaDescription' => 6, 'MetaKeywords' => 7, 'Template' => 8, 'IsActive' => 9, 'IsHidden' => 10, 'Rank' => 11, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'cre8MenuTypeId' => 1, 'name' => 2, 'cre8ContentTypeId' => 3, 'slug' => 4, 'metaTitle' => 5, 'metaDescription' => 6, 'metaKeywords' => 7, 'template' => 8, 'isActive' => 9, 'isHidden' => 10, 'rank' => 11, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::CRE8_MENU_TYPE_ID => 1, self::NAME => 2, self::CRE8_CONTENT_TYPE_ID => 3, self::SLUG => 4, self::META_TITLE => 5, self::META_DESCRIPTION => 6, self::META_KEYWORDS => 7, self::TEMPLATE => 8, self::IS_ACTIVE => 9, self::IS_HIDDEN => 10, self::RANK => 11, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'cre8_menu_type_id' => 1, 'name' => 2, 'cre8_content_type_id' => 3, 'slug' => 4, 'meta_title' => 5, 'meta_description' => 6, 'meta_keywords' => 7, 'template' => 8, 'is_active' => 9, 'is_hidden' => 10, 'rank' => 11, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new Cre8MenuContentMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. Cre8MenuContentPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(Cre8MenuContentPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(Cre8MenuContentPeer::ID);

		$criteria->addSelectColumn(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID);

		$criteria->addSelectColumn(Cre8MenuContentPeer::NAME);

		$criteria->addSelectColumn(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID);

		$criteria->addSelectColumn(Cre8MenuContentPeer::SLUG);

		$criteria->addSelectColumn(Cre8MenuContentPeer::META_TITLE);

		$criteria->addSelectColumn(Cre8MenuContentPeer::META_DESCRIPTION);

		$criteria->addSelectColumn(Cre8MenuContentPeer::META_KEYWORDS);

		$criteria->addSelectColumn(Cre8MenuContentPeer::TEMPLATE);

		$criteria->addSelectColumn(Cre8MenuContentPeer::IS_ACTIVE);

		$criteria->addSelectColumn(Cre8MenuContentPeer::IS_HIDDEN);

		$criteria->addSelectColumn(Cre8MenuContentPeer::RANK);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Cre8MenuContentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Cre8MenuContent
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = Cre8MenuContentPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return Cre8MenuContentPeer::populateObjects(Cre8MenuContentPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Cre8MenuContent $value A Cre8MenuContent object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Cre8MenuContent $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Cre8MenuContent object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Cre8MenuContent) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Cre8MenuContent object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Cre8MenuContent Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = Cre8MenuContentPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = Cre8MenuContentPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				Cre8MenuContentPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Cre8MenuType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCre8MenuType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Cre8MenuContentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Cre8ContentType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCre8ContentType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Cre8MenuContentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Cre8MenuContent objects pre-filled with their Cre8MenuType objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Cre8MenuContent objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCre8MenuType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Cre8MenuContentPeer::addSelectColumns($c);
		$startcol = (Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS);
		Cre8MenuTypePeer::addSelectColumns($c);

		$c->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Cre8MenuContentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Cre8MenuContentPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Cre8MenuContentPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Cre8MenuTypePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Cre8MenuTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Cre8MenuTypePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Cre8MenuTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Cre8MenuContent) to $obj2 (Cre8MenuType)
				$obj2->addCre8MenuContent($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Cre8MenuContent objects pre-filled with their Cre8ContentType objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Cre8MenuContent objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCre8ContentType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Cre8MenuContentPeer::addSelectColumns($c);
		$startcol = (Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS);
		Cre8ContentTypePeer::addSelectColumns($c);

		$c->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Cre8MenuContentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Cre8MenuContentPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Cre8MenuContentPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Cre8ContentTypePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Cre8ContentTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Cre8ContentTypePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Cre8ContentTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Cre8MenuContent) to $obj2 (Cre8ContentType)
				$obj2->addCre8MenuContent($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Cre8MenuContentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);
		$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Cre8MenuContent objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Cre8MenuContent objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Cre8MenuContentPeer::addSelectColumns($c);
		$startcol2 = (Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS);

		Cre8MenuTypePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Cre8MenuTypePeer::NUM_COLUMNS - Cre8MenuTypePeer::NUM_LAZY_LOAD_COLUMNS);

		Cre8ContentTypePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Cre8ContentTypePeer::NUM_COLUMNS - Cre8ContentTypePeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);
		$c->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Cre8MenuContentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Cre8MenuContentPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Cre8MenuContentPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Cre8MenuType rows

			$key2 = Cre8MenuTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = Cre8MenuTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Cre8MenuTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Cre8MenuTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Cre8MenuContent) to the collection in $obj2 (Cre8MenuType)
				$obj2->addCre8MenuContent($obj1);
			} // if joined row not null

			// Add objects for joined Cre8ContentType rows

			$key3 = Cre8ContentTypePeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = Cre8ContentTypePeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = Cre8ContentTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Cre8ContentTypePeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Cre8MenuContent) to the collection in $obj3 (Cre8ContentType)
				$obj3->addCre8MenuContent($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Cre8MenuType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCre8MenuType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Cre8ContentType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCre8ContentType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Cre8MenuContentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Cre8MenuContent objects pre-filled with all related objects except Cre8MenuType.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Cre8MenuContent objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCre8MenuType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Cre8MenuContentPeer::addSelectColumns($c);
		$startcol2 = (Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS);

		Cre8ContentTypePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Cre8ContentTypePeer::NUM_COLUMNS - Cre8ContentTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID,), array(Cre8ContentTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Cre8MenuContentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Cre8MenuContentPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Cre8MenuContentPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Cre8ContentType rows

				$key2 = Cre8ContentTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Cre8ContentTypePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Cre8ContentTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Cre8ContentTypePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Cre8MenuContent) to the collection in $obj2 (Cre8ContentType)
				$obj2->addCre8MenuContent($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Cre8MenuContent objects pre-filled with all related objects except Cre8ContentType.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Cre8MenuContent objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCre8ContentType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Cre8MenuContentPeer::addSelectColumns($c);
		$startcol2 = (Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS);

		Cre8MenuTypePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Cre8MenuTypePeer::NUM_COLUMNS - Cre8MenuTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID,), array(Cre8MenuTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Cre8MenuContentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Cre8MenuContentPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Cre8MenuContentPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Cre8MenuContentPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Cre8MenuType rows

				$key2 = Cre8MenuTypePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Cre8MenuTypePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Cre8MenuTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Cre8MenuTypePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Cre8MenuContent) to the collection in $obj2 (Cre8MenuType)
				$obj2->addCre8MenuContent($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return Cre8MenuContentPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Cre8MenuContent or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cre8MenuContent object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCre8MenuContentPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Cre8MenuContent object
		}

		if ($criteria->containsKey(Cre8MenuContentPeer::ID) && $criteria->keyContainsValue(Cre8MenuContentPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.Cre8MenuContentPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Cre8MenuContent or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cre8MenuContent object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCre8MenuContentPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(Cre8MenuContentPeer::ID);
			$selectCriteria->add(Cre8MenuContentPeer::ID, $criteria->remove(Cre8MenuContentPeer::ID), $comparison);

		} else { // $values is Cre8MenuContent object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseCre8MenuContentPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseCre8MenuContentPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the cre8_menu_content table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += Cre8MenuContentPeer::doOnDeleteCascade(new Criteria(Cre8MenuContentPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(Cre8MenuContentPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Cre8MenuContent or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Cre8MenuContent object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			Cre8MenuContentPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Cre8MenuContent) {
			// invalidate the cache for this single object
			Cre8MenuContentPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(Cre8MenuContentPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				Cre8MenuContentPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += Cre8MenuContentPeer::doOnDeleteCascade($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					Cre8MenuContentPeer::clearInstancePool();
				} else { // it's a PK or object
					Cre8MenuContentPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in Cre8MenuContentTypeFlashPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			Cre8MenuContentTypeFlashPeer::clearInstancePool();

			// invalidate objects in Cre8MenuContentTypeImagePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			Cre8MenuContentTypeImagePeer::clearInstancePool();

			// invalidate objects in Cre8MenuContentTypeCmsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			Cre8MenuContentTypeCmsPeer::clearInstancePool();

			// invalidate objects in Cre8MenuContentTypeInternalLinkPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			Cre8MenuContentTypeInternalLinkPeer::clearInstancePool();

			// invalidate objects in MenuTopBannerPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			MenuTopBannerPeer::clearInstancePool();

			// invalidate objects in MenuContentTypeCmsWithImagePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			MenuContentTypeCmsWithImagePeer::clearInstancePool();

			// invalidate objects in MenuContentTypeInternalLinkWithImagePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			MenuContentTypeInternalLinkWithImagePeer::clearInstancePool();

			// invalidate objects in MenuFooterLinkMenuPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			MenuFooterLinkMenuPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = Cre8MenuContentPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related Cre8MenuContentTypeFlash objects
			$c = new Criteria(Cre8MenuContentTypeFlashPeer::DATABASE_NAME);
			
			$c->add(Cre8MenuContentTypeFlashPeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += Cre8MenuContentTypeFlashPeer::doDelete($c, $con);

			// delete related Cre8MenuContentTypeImage objects
			$c = new Criteria(Cre8MenuContentTypeImagePeer::DATABASE_NAME);
			
			$c->add(Cre8MenuContentTypeImagePeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += Cre8MenuContentTypeImagePeer::doDelete($c, $con);

			// delete related Cre8MenuContentTypeCms objects
			$c = new Criteria(Cre8MenuContentTypeCmsPeer::DATABASE_NAME);
			
			$c->add(Cre8MenuContentTypeCmsPeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += Cre8MenuContentTypeCmsPeer::doDelete($c, $con);

			// delete related Cre8MenuContentTypeInternalLink objects
			$c = new Criteria(Cre8MenuContentTypeInternalLinkPeer::DATABASE_NAME);
			
			$c->add(Cre8MenuContentTypeInternalLinkPeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += Cre8MenuContentTypeInternalLinkPeer::doDelete($c, $con);

			// delete related MenuTopBanner objects
			$c = new Criteria(MenuTopBannerPeer::DATABASE_NAME);
			
			$c->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += MenuTopBannerPeer::doDelete($c, $con);

			// delete related MenuContentTypeCmsWithImage objects
			$c = new Criteria(MenuContentTypeCmsWithImagePeer::DATABASE_NAME);
			
			$c->add(MenuContentTypeCmsWithImagePeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += MenuContentTypeCmsWithImagePeer::doDelete($c, $con);

			// delete related MenuContentTypeInternalLinkWithImage objects
			$c = new Criteria(MenuContentTypeInternalLinkWithImagePeer::DATABASE_NAME);
			
			$c->add(MenuContentTypeInternalLinkWithImagePeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += MenuContentTypeInternalLinkWithImagePeer::doDelete($c, $con);

			// delete related MenuFooterLinkMenu objects
			$c = new Criteria(MenuFooterLinkMenuPeer::DATABASE_NAME);
			
			$c->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $obj->getId());
			$affectedRows += MenuFooterLinkMenuPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given Cre8MenuContent object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Cre8MenuContent $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Cre8MenuContent $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(Cre8MenuContentPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(Cre8MenuContentPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(Cre8MenuContentPeer::DATABASE_NAME, Cre8MenuContentPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = Cre8MenuContentPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Cre8MenuContent
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = Cre8MenuContentPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		$criteria->add(Cre8MenuContentPeer::ID, $pk);

		$v = Cre8MenuContentPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
			$criteria->add(Cre8MenuContentPeer::ID, $pks, Criteria::IN);
			$objs = Cre8MenuContentPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseCre8MenuContentPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the Cre8MenuContentPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the Cre8MenuContentPeer class:
//
// Propel::getDatabaseMap(Cre8MenuContentPeer::DATABASE_NAME)->addTableBuilder(Cre8MenuContentPeer::TABLE_NAME, Cre8MenuContentPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseCre8MenuContentPeer::DATABASE_NAME)->addTableBuilder(BaseCre8MenuContentPeer::TABLE_NAME, BaseCre8MenuContentPeer::getMapBuilder());

