<?php

/**
 * Base class that represents a row from the 'cre8_menu_content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jun  2 04:40:01 2009
 *
 * @package    plugins.cre8MenuPlugin.lib.model.om
 */
abstract class BaseCre8MenuContent extends BaseObject  implements Persistent {


  const PEER = 'Cre8MenuContentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Cre8MenuContentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the cre8_menu_type_id field.
	 * @var        int
	 */
	protected $cre8_menu_type_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the cre8_content_type_id field.
	 * @var        int
	 */
	protected $cre8_content_type_id;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the meta_title field.
	 * @var        string
	 */
	protected $meta_title;

	/**
	 * The value for the meta_description field.
	 * @var        string
	 */
	protected $meta_description;

	/**
	 * The value for the meta_keywords field.
	 * @var        string
	 */
	protected $meta_keywords;

	/**
	 * The value for the template field.
	 * @var        string
	 */
	protected $template;

	/**
	 * The value for the is_active field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_active;

	/**
	 * The value for the is_hidden field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_hidden;

	/**
	 * The value for the rank field.
	 * @var        int
	 */
	protected $rank;

	/**
	 * @var        Cre8MenuType
	 */
	protected $aCre8MenuType;

	/**
	 * @var        Cre8ContentType
	 */
	protected $aCre8ContentType;

	/**
	 * @var        array Cre8MenuContentTypeFlash[] Collection to store aggregation of Cre8MenuContentTypeFlash objects.
	 */
	protected $collCre8MenuContentTypeFlashs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCre8MenuContentTypeFlashs.
	 */
	private $lastCre8MenuContentTypeFlashCriteria = null;

	/**
	 * @var        array Cre8MenuContentTypeImage[] Collection to store aggregation of Cre8MenuContentTypeImage objects.
	 */
	protected $collCre8MenuContentTypeImages;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCre8MenuContentTypeImages.
	 */
	private $lastCre8MenuContentTypeImageCriteria = null;

	/**
	 * @var        array Cre8MenuContentTypeCms[] Collection to store aggregation of Cre8MenuContentTypeCms objects.
	 */
	protected $collCre8MenuContentTypeCmss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCre8MenuContentTypeCmss.
	 */
	private $lastCre8MenuContentTypeCmsCriteria = null;

	/**
	 * @var        array Cre8MenuContentTypeInternalLink[] Collection to store aggregation of Cre8MenuContentTypeInternalLink objects.
	 */
	protected $collCre8MenuContentTypeInternalLinks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCre8MenuContentTypeInternalLinks.
	 */
	private $lastCre8MenuContentTypeInternalLinkCriteria = null;

	/**
	 * @var        array MenuTopBanner[] Collection to store aggregation of MenuTopBanner objects.
	 */
	protected $collMenuTopBanners;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMenuTopBanners.
	 */
	private $lastMenuTopBannerCriteria = null;

	/**
	 * @var        array MenuContentTypeCmsWithImage[] Collection to store aggregation of MenuContentTypeCmsWithImage objects.
	 */
	protected $collMenuContentTypeCmsWithImages;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMenuContentTypeCmsWithImages.
	 */
	private $lastMenuContentTypeCmsWithImageCriteria = null;

	/**
	 * @var        array MenuContentTypeInternalLinkWithImage[] Collection to store aggregation of MenuContentTypeInternalLinkWithImage objects.
	 */
	protected $collMenuContentTypeInternalLinkWithImages;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMenuContentTypeInternalLinkWithImages.
	 */
	private $lastMenuContentTypeInternalLinkWithImageCriteria = null;

	/**
	 * @var        array MenuFooterLinkMenu[] Collection to store aggregation of MenuFooterLinkMenu objects.
	 */
	protected $collMenuFooterLinkMenus;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMenuFooterLinkMenus.
	 */
	private $lastMenuFooterLinkMenuCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCre8MenuContent object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_active = true;
		$this->is_hidden = false;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [cre8_menu_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getCre8MenuTypeId()
	{
		return $this->cre8_menu_type_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [cre8_content_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getCre8ContentTypeId()
	{
		return $this->cre8_content_type_id;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [meta_title] column value.
	 * 
	 * @return     string
	 */
	public function getMetaTitle()
	{
		return $this->meta_title;
	}

	/**
	 * Get the [meta_description] column value.
	 * 
	 * @return     string
	 */
	public function getMetaDescription()
	{
		return $this->meta_description;
	}

	/**
	 * Get the [meta_keywords] column value.
	 * 
	 * @return     string
	 */
	public function getMetaKeywords()
	{
		return $this->meta_keywords;
	}

	/**
	 * Get the [template] column value.
	 * 
	 * @return     string
	 */
	public function getTemplate()
	{
		return $this->template;
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Get the [is_hidden] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsHidden()
	{
		return $this->is_hidden;
	}

	/**
	 * Get the [rank] column value.
	 * 
	 * @return     int
	 */
	public function getRank()
	{
		return $this->rank;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [cre8_menu_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setCre8MenuTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cre8_menu_type_id !== $v) {
			$this->cre8_menu_type_id = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::CRE8_MENU_TYPE_ID;
		}

		if ($this->aCre8MenuType !== null && $this->aCre8MenuType->getId() !== $v) {
			$this->aCre8MenuType = null;
		}

		return $this;
	} // setCre8MenuTypeId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [cre8_content_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setCre8ContentTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cre8_content_type_id !== $v) {
			$this->cre8_content_type_id = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID;
		}

		if ($this->aCre8ContentType !== null && $this->aCre8ContentType->getId() !== $v) {
			$this->aCre8ContentType = null;
		}

		return $this;
	} // setCre8ContentTypeId()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [meta_title] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setMetaTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_title !== $v) {
			$this->meta_title = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::META_TITLE;
		}

		return $this;
	} // setMetaTitle()

	/**
	 * Set the value of [meta_description] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setMetaDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_description !== $v) {
			$this->meta_description = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::META_DESCRIPTION;
		}

		return $this;
	} // setMetaDescription()

	/**
	 * Set the value of [meta_keywords] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setMetaKeywords($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_keywords !== $v) {
			$this->meta_keywords = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::META_KEYWORDS;
		}

		return $this;
	} // setMetaKeywords()

	/**
	 * Set the value of [template] column.
	 * 
	 * @param      string $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setTemplate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->template !== $v) {
			$this->template = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::TEMPLATE;
		}

		return $this;
	} // setTemplate()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_active !== $v || $v === true) {
			$this->is_active = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Set the value of [is_hidden] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setIsHidden($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_hidden !== $v || $v === false) {
			$this->is_hidden = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::IS_HIDDEN;
		}

		return $this;
	} // setIsHidden()

	/**
	 * Set the value of [rank] column.
	 * 
	 * @param      int $v new value
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 */
	public function setRank($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rank !== $v) {
			$this->rank = $v;
			$this->modifiedColumns[] = Cre8MenuContentPeer::RANK;
		}

		return $this;
	} // setRank()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(Cre8MenuContentPeer::IS_ACTIVE,Cre8MenuContentPeer::IS_HIDDEN))) {
				return false;
			}

			if ($this->is_active !== true) {
				return false;
			}

			if ($this->is_hidden !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->cre8_menu_type_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->cre8_content_type_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->slug = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->meta_title = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->meta_description = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->meta_keywords = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->template = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->is_active = ($row[$startcol + 9] !== null) ? (boolean) $row[$startcol + 9] : null;
			$this->is_hidden = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->rank = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = Cre8MenuContentPeer::NUM_COLUMNS - Cre8MenuContentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Cre8MenuContent object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCre8MenuType !== null && $this->cre8_menu_type_id !== $this->aCre8MenuType->getId()) {
			$this->aCre8MenuType = null;
		}
		if ($this->aCre8ContentType !== null && $this->cre8_content_type_id !== $this->aCre8ContentType->getId()) {
			$this->aCre8ContentType = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Cre8MenuContentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCre8MenuType = null;
			$this->aCre8ContentType = null;
			$this->collCre8MenuContentTypeFlashs = null;
			$this->lastCre8MenuContentTypeFlashCriteria = null;

			$this->collCre8MenuContentTypeImages = null;
			$this->lastCre8MenuContentTypeImageCriteria = null;

			$this->collCre8MenuContentTypeCmss = null;
			$this->lastCre8MenuContentTypeCmsCriteria = null;

			$this->collCre8MenuContentTypeInternalLinks = null;
			$this->lastCre8MenuContentTypeInternalLinkCriteria = null;

			$this->collMenuTopBanners = null;
			$this->lastMenuTopBannerCriteria = null;

			$this->collMenuContentTypeCmsWithImages = null;
			$this->lastMenuContentTypeCmsWithImageCriteria = null;

			$this->collMenuContentTypeInternalLinkWithImages = null;
			$this->lastMenuContentTypeInternalLinkWithImageCriteria = null;

			$this->collMenuFooterLinkMenus = null;
			$this->lastMenuFooterLinkMenuCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContent:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			Cre8MenuContentPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCre8MenuContent:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCre8MenuContent:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Cre8MenuContentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCre8MenuContent:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			Cre8MenuContentPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCre8MenuType !== null) {
				if ($this->aCre8MenuType->isModified() || $this->aCre8MenuType->isNew()) {
					$affectedRows += $this->aCre8MenuType->save($con);
				}
				$this->setCre8MenuType($this->aCre8MenuType);
			}

			if ($this->aCre8ContentType !== null) {
				if ($this->aCre8ContentType->isModified() || $this->aCre8ContentType->isNew()) {
					$affectedRows += $this->aCre8ContentType->save($con);
				}
				$this->setCre8ContentType($this->aCre8ContentType);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = Cre8MenuContentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = Cre8MenuContentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += Cre8MenuContentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCre8MenuContentTypeFlashs !== null) {
				foreach ($this->collCre8MenuContentTypeFlashs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCre8MenuContentTypeImages !== null) {
				foreach ($this->collCre8MenuContentTypeImages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCre8MenuContentTypeCmss !== null) {
				foreach ($this->collCre8MenuContentTypeCmss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCre8MenuContentTypeInternalLinks !== null) {
				foreach ($this->collCre8MenuContentTypeInternalLinks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMenuTopBanners !== null) {
				foreach ($this->collMenuTopBanners as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMenuContentTypeCmsWithImages !== null) {
				foreach ($this->collMenuContentTypeCmsWithImages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMenuContentTypeInternalLinkWithImages !== null) {
				foreach ($this->collMenuContentTypeInternalLinkWithImages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMenuFooterLinkMenus !== null) {
				foreach ($this->collMenuFooterLinkMenus as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCre8MenuType !== null) {
				if (!$this->aCre8MenuType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCre8MenuType->getValidationFailures());
				}
			}

			if ($this->aCre8ContentType !== null) {
				if (!$this->aCre8ContentType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCre8ContentType->getValidationFailures());
				}
			}


			if (($retval = Cre8MenuContentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCre8MenuContentTypeFlashs !== null) {
					foreach ($this->collCre8MenuContentTypeFlashs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCre8MenuContentTypeImages !== null) {
					foreach ($this->collCre8MenuContentTypeImages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCre8MenuContentTypeCmss !== null) {
					foreach ($this->collCre8MenuContentTypeCmss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCre8MenuContentTypeInternalLinks !== null) {
					foreach ($this->collCre8MenuContentTypeInternalLinks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMenuTopBanners !== null) {
					foreach ($this->collMenuTopBanners as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMenuContentTypeCmsWithImages !== null) {
					foreach ($this->collMenuContentTypeCmsWithImages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMenuContentTypeInternalLinkWithImages !== null) {
					foreach ($this->collMenuContentTypeInternalLinkWithImages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMenuFooterLinkMenus !== null) {
					foreach ($this->collMenuFooterLinkMenus as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Cre8MenuContentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCre8MenuTypeId();
				break;
			case 2:
				return $this->getName();
				break;
			case 3:
				return $this->getCre8ContentTypeId();
				break;
			case 4:
				return $this->getSlug();
				break;
			case 5:
				return $this->getMetaTitle();
				break;
			case 6:
				return $this->getMetaDescription();
				break;
			case 7:
				return $this->getMetaKeywords();
				break;
			case 8:
				return $this->getTemplate();
				break;
			case 9:
				return $this->getIsActive();
				break;
			case 10:
				return $this->getIsHidden();
				break;
			case 11:
				return $this->getRank();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = Cre8MenuContentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCre8MenuTypeId(),
			$keys[2] => $this->getName(),
			$keys[3] => $this->getCre8ContentTypeId(),
			$keys[4] => $this->getSlug(),
			$keys[5] => $this->getMetaTitle(),
			$keys[6] => $this->getMetaDescription(),
			$keys[7] => $this->getMetaKeywords(),
			$keys[8] => $this->getTemplate(),
			$keys[9] => $this->getIsActive(),
			$keys[10] => $this->getIsHidden(),
			$keys[11] => $this->getRank(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Cre8MenuContentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCre8MenuTypeId($value);
				break;
			case 2:
				$this->setName($value);
				break;
			case 3:
				$this->setCre8ContentTypeId($value);
				break;
			case 4:
				$this->setSlug($value);
				break;
			case 5:
				$this->setMetaTitle($value);
				break;
			case 6:
				$this->setMetaDescription($value);
				break;
			case 7:
				$this->setMetaKeywords($value);
				break;
			case 8:
				$this->setTemplate($value);
				break;
			case 9:
				$this->setIsActive($value);
				break;
			case 10:
				$this->setIsHidden($value);
				break;
			case 11:
				$this->setRank($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Cre8MenuContentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCre8MenuTypeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCre8ContentTypeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSlug($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMetaTitle($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMetaDescription($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMetaKeywords($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTemplate($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIsActive($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIsHidden($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setRank($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);

		if ($this->isColumnModified(Cre8MenuContentPeer::ID)) $criteria->add(Cre8MenuContentPeer::ID, $this->id);
		if ($this->isColumnModified(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID)) $criteria->add(Cre8MenuContentPeer::CRE8_MENU_TYPE_ID, $this->cre8_menu_type_id);
		if ($this->isColumnModified(Cre8MenuContentPeer::NAME)) $criteria->add(Cre8MenuContentPeer::NAME, $this->name);
		if ($this->isColumnModified(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID)) $criteria->add(Cre8MenuContentPeer::CRE8_CONTENT_TYPE_ID, $this->cre8_content_type_id);
		if ($this->isColumnModified(Cre8MenuContentPeer::SLUG)) $criteria->add(Cre8MenuContentPeer::SLUG, $this->slug);
		if ($this->isColumnModified(Cre8MenuContentPeer::META_TITLE)) $criteria->add(Cre8MenuContentPeer::META_TITLE, $this->meta_title);
		if ($this->isColumnModified(Cre8MenuContentPeer::META_DESCRIPTION)) $criteria->add(Cre8MenuContentPeer::META_DESCRIPTION, $this->meta_description);
		if ($this->isColumnModified(Cre8MenuContentPeer::META_KEYWORDS)) $criteria->add(Cre8MenuContentPeer::META_KEYWORDS, $this->meta_keywords);
		if ($this->isColumnModified(Cre8MenuContentPeer::TEMPLATE)) $criteria->add(Cre8MenuContentPeer::TEMPLATE, $this->template);
		if ($this->isColumnModified(Cre8MenuContentPeer::IS_ACTIVE)) $criteria->add(Cre8MenuContentPeer::IS_ACTIVE, $this->is_active);
		if ($this->isColumnModified(Cre8MenuContentPeer::IS_HIDDEN)) $criteria->add(Cre8MenuContentPeer::IS_HIDDEN, $this->is_hidden);
		if ($this->isColumnModified(Cre8MenuContentPeer::RANK)) $criteria->add(Cre8MenuContentPeer::RANK, $this->rank);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);

		$criteria->add(Cre8MenuContentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Cre8MenuContent (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCre8MenuTypeId($this->cre8_menu_type_id);

		$copyObj->setName($this->name);

		$copyObj->setCre8ContentTypeId($this->cre8_content_type_id);

		$copyObj->setSlug($this->slug);

		$copyObj->setMetaTitle($this->meta_title);

		$copyObj->setMetaDescription($this->meta_description);

		$copyObj->setMetaKeywords($this->meta_keywords);

		$copyObj->setTemplate($this->template);

		$copyObj->setIsActive($this->is_active);

		$copyObj->setIsHidden($this->is_hidden);

		$copyObj->setRank($this->rank);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCre8MenuContentTypeFlashs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCre8MenuContentTypeFlash($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCre8MenuContentTypeImages() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCre8MenuContentTypeImage($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCre8MenuContentTypeCmss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCre8MenuContentTypeCms($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCre8MenuContentTypeInternalLinks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCre8MenuContentTypeInternalLink($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMenuTopBanners() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMenuTopBanner($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMenuContentTypeCmsWithImages() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMenuContentTypeCmsWithImage($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMenuContentTypeInternalLinkWithImages() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMenuContentTypeInternalLinkWithImage($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMenuFooterLinkMenus() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMenuFooterLinkMenu($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Cre8MenuContent Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Cre8MenuContentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Cre8MenuContentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Cre8MenuType object.
	 *
	 * @param      Cre8MenuType $v
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCre8MenuType(Cre8MenuType $v = null)
	{
		if ($v === null) {
			$this->setCre8MenuTypeId(NULL);
		} else {
			$this->setCre8MenuTypeId($v->getId());
		}

		$this->aCre8MenuType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cre8MenuType object, it will not be re-added.
		if ($v !== null) {
			$v->addCre8MenuContent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cre8MenuType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cre8MenuType The associated Cre8MenuType object.
	 * @throws     PropelException
	 */
	public function getCre8MenuType(PropelPDO $con = null)
	{
		if ($this->aCre8MenuType === null && ($this->cre8_menu_type_id !== null)) {
			$c = new Criteria(Cre8MenuTypePeer::DATABASE_NAME);
			$c->add(Cre8MenuTypePeer::ID, $this->cre8_menu_type_id);
			$this->aCre8MenuType = Cre8MenuTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCre8MenuType->addCre8MenuContents($this);
			 */
		}
		return $this->aCre8MenuType;
	}

	/**
	 * Declares an association between this object and a Cre8ContentType object.
	 *
	 * @param      Cre8ContentType $v
	 * @return     Cre8MenuContent The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCre8ContentType(Cre8ContentType $v = null)
	{
		if ($v === null) {
			$this->setCre8ContentTypeId(NULL);
		} else {
			$this->setCre8ContentTypeId($v->getId());
		}

		$this->aCre8ContentType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cre8ContentType object, it will not be re-added.
		if ($v !== null) {
			$v->addCre8MenuContent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cre8ContentType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cre8ContentType The associated Cre8ContentType object.
	 * @throws     PropelException
	 */
	public function getCre8ContentType(PropelPDO $con = null)
	{
		if ($this->aCre8ContentType === null && ($this->cre8_content_type_id !== null)) {
			$c = new Criteria(Cre8ContentTypePeer::DATABASE_NAME);
			$c->add(Cre8ContentTypePeer::ID, $this->cre8_content_type_id);
			$this->aCre8ContentType = Cre8ContentTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCre8ContentType->addCre8MenuContents($this);
			 */
		}
		return $this->aCre8ContentType;
	}

	/**
	 * Clears out the collCre8MenuContentTypeFlashs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCre8MenuContentTypeFlashs()
	 */
	public function clearCre8MenuContentTypeFlashs()
	{
		$this->collCre8MenuContentTypeFlashs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCre8MenuContentTypeFlashs collection (array).
	 *
	 * By default this just sets the collCre8MenuContentTypeFlashs collection to an empty array (like clearcollCre8MenuContentTypeFlashs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCre8MenuContentTypeFlashs()
	{
		$this->collCre8MenuContentTypeFlashs = array();
	}

	/**
	 * Gets an array of Cre8MenuContentTypeFlash objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related Cre8MenuContentTypeFlashs from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cre8MenuContentTypeFlash[]
	 * @throws     PropelException
	 */
	public function getCre8MenuContentTypeFlashs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCre8MenuContentTypeFlashs === null) {
			if ($this->isNew()) {
			   $this->collCre8MenuContentTypeFlashs = array();
			} else {

				$criteria->add(Cre8MenuContentTypeFlashPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeFlashPeer::addSelectColumns($criteria);
				$this->collCre8MenuContentTypeFlashs = Cre8MenuContentTypeFlashPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Cre8MenuContentTypeFlashPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeFlashPeer::addSelectColumns($criteria);
				if (!isset($this->lastCre8MenuContentTypeFlashCriteria) || !$this->lastCre8MenuContentTypeFlashCriteria->equals($criteria)) {
					$this->collCre8MenuContentTypeFlashs = Cre8MenuContentTypeFlashPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCre8MenuContentTypeFlashCriteria = $criteria;
		return $this->collCre8MenuContentTypeFlashs;
	}

	/**
	 * Returns the number of related Cre8MenuContentTypeFlash objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cre8MenuContentTypeFlash objects.
	 * @throws     PropelException
	 */
	public function countCre8MenuContentTypeFlashs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCre8MenuContentTypeFlashs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Cre8MenuContentTypeFlashPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = Cre8MenuContentTypeFlashPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Cre8MenuContentTypeFlashPeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastCre8MenuContentTypeFlashCriteria) || !$this->lastCre8MenuContentTypeFlashCriteria->equals($criteria)) {
					$count = Cre8MenuContentTypeFlashPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCre8MenuContentTypeFlashs);
				}
			} else {
				$count = count($this->collCre8MenuContentTypeFlashs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cre8MenuContentTypeFlash object to this object
	 * through the Cre8MenuContentTypeFlash foreign key attribute.
	 *
	 * @param      Cre8MenuContentTypeFlash $l Cre8MenuContentTypeFlash
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCre8MenuContentTypeFlash(Cre8MenuContentTypeFlash $l)
	{
		if ($this->collCre8MenuContentTypeFlashs === null) {
			$this->initCre8MenuContentTypeFlashs();
		}
		if (!in_array($l, $this->collCre8MenuContentTypeFlashs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCre8MenuContentTypeFlashs, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collCre8MenuContentTypeImages collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCre8MenuContentTypeImages()
	 */
	public function clearCre8MenuContentTypeImages()
	{
		$this->collCre8MenuContentTypeImages = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCre8MenuContentTypeImages collection (array).
	 *
	 * By default this just sets the collCre8MenuContentTypeImages collection to an empty array (like clearcollCre8MenuContentTypeImages());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCre8MenuContentTypeImages()
	{
		$this->collCre8MenuContentTypeImages = array();
	}

	/**
	 * Gets an array of Cre8MenuContentTypeImage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related Cre8MenuContentTypeImages from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cre8MenuContentTypeImage[]
	 * @throws     PropelException
	 */
	public function getCre8MenuContentTypeImages($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCre8MenuContentTypeImages === null) {
			if ($this->isNew()) {
			   $this->collCre8MenuContentTypeImages = array();
			} else {

				$criteria->add(Cre8MenuContentTypeImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeImagePeer::addSelectColumns($criteria);
				$this->collCre8MenuContentTypeImages = Cre8MenuContentTypeImagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Cre8MenuContentTypeImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeImagePeer::addSelectColumns($criteria);
				if (!isset($this->lastCre8MenuContentTypeImageCriteria) || !$this->lastCre8MenuContentTypeImageCriteria->equals($criteria)) {
					$this->collCre8MenuContentTypeImages = Cre8MenuContentTypeImagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCre8MenuContentTypeImageCriteria = $criteria;
		return $this->collCre8MenuContentTypeImages;
	}

	/**
	 * Returns the number of related Cre8MenuContentTypeImage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cre8MenuContentTypeImage objects.
	 * @throws     PropelException
	 */
	public function countCre8MenuContentTypeImages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCre8MenuContentTypeImages === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Cre8MenuContentTypeImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = Cre8MenuContentTypeImagePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Cre8MenuContentTypeImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastCre8MenuContentTypeImageCriteria) || !$this->lastCre8MenuContentTypeImageCriteria->equals($criteria)) {
					$count = Cre8MenuContentTypeImagePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCre8MenuContentTypeImages);
				}
			} else {
				$count = count($this->collCre8MenuContentTypeImages);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cre8MenuContentTypeImage object to this object
	 * through the Cre8MenuContentTypeImage foreign key attribute.
	 *
	 * @param      Cre8MenuContentTypeImage $l Cre8MenuContentTypeImage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCre8MenuContentTypeImage(Cre8MenuContentTypeImage $l)
	{
		if ($this->collCre8MenuContentTypeImages === null) {
			$this->initCre8MenuContentTypeImages();
		}
		if (!in_array($l, $this->collCre8MenuContentTypeImages, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCre8MenuContentTypeImages, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collCre8MenuContentTypeCmss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCre8MenuContentTypeCmss()
	 */
	public function clearCre8MenuContentTypeCmss()
	{
		$this->collCre8MenuContentTypeCmss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCre8MenuContentTypeCmss collection (array).
	 *
	 * By default this just sets the collCre8MenuContentTypeCmss collection to an empty array (like clearcollCre8MenuContentTypeCmss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCre8MenuContentTypeCmss()
	{
		$this->collCre8MenuContentTypeCmss = array();
	}

	/**
	 * Gets an array of Cre8MenuContentTypeCms objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related Cre8MenuContentTypeCmss from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cre8MenuContentTypeCms[]
	 * @throws     PropelException
	 */
	public function getCre8MenuContentTypeCmss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCre8MenuContentTypeCmss === null) {
			if ($this->isNew()) {
			   $this->collCre8MenuContentTypeCmss = array();
			} else {

				$criteria->add(Cre8MenuContentTypeCmsPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeCmsPeer::addSelectColumns($criteria);
				$this->collCre8MenuContentTypeCmss = Cre8MenuContentTypeCmsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Cre8MenuContentTypeCmsPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeCmsPeer::addSelectColumns($criteria);
				if (!isset($this->lastCre8MenuContentTypeCmsCriteria) || !$this->lastCre8MenuContentTypeCmsCriteria->equals($criteria)) {
					$this->collCre8MenuContentTypeCmss = Cre8MenuContentTypeCmsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCre8MenuContentTypeCmsCriteria = $criteria;
		return $this->collCre8MenuContentTypeCmss;
	}

	/**
	 * Returns the number of related Cre8MenuContentTypeCms objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cre8MenuContentTypeCms objects.
	 * @throws     PropelException
	 */
	public function countCre8MenuContentTypeCmss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCre8MenuContentTypeCmss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Cre8MenuContentTypeCmsPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = Cre8MenuContentTypeCmsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Cre8MenuContentTypeCmsPeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastCre8MenuContentTypeCmsCriteria) || !$this->lastCre8MenuContentTypeCmsCriteria->equals($criteria)) {
					$count = Cre8MenuContentTypeCmsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCre8MenuContentTypeCmss);
				}
			} else {
				$count = count($this->collCre8MenuContentTypeCmss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cre8MenuContentTypeCms object to this object
	 * through the Cre8MenuContentTypeCms foreign key attribute.
	 *
	 * @param      Cre8MenuContentTypeCms $l Cre8MenuContentTypeCms
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCre8MenuContentTypeCms(Cre8MenuContentTypeCms $l)
	{
		if ($this->collCre8MenuContentTypeCmss === null) {
			$this->initCre8MenuContentTypeCmss();
		}
		if (!in_array($l, $this->collCre8MenuContentTypeCmss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCre8MenuContentTypeCmss, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collCre8MenuContentTypeInternalLinks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCre8MenuContentTypeInternalLinks()
	 */
	public function clearCre8MenuContentTypeInternalLinks()
	{
		$this->collCre8MenuContentTypeInternalLinks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCre8MenuContentTypeInternalLinks collection (array).
	 *
	 * By default this just sets the collCre8MenuContentTypeInternalLinks collection to an empty array (like clearcollCre8MenuContentTypeInternalLinks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCre8MenuContentTypeInternalLinks()
	{
		$this->collCre8MenuContentTypeInternalLinks = array();
	}

	/**
	 * Gets an array of Cre8MenuContentTypeInternalLink objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related Cre8MenuContentTypeInternalLinks from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cre8MenuContentTypeInternalLink[]
	 * @throws     PropelException
	 */
	public function getCre8MenuContentTypeInternalLinks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCre8MenuContentTypeInternalLinks === null) {
			if ($this->isNew()) {
			   $this->collCre8MenuContentTypeInternalLinks = array();
			} else {

				$criteria->add(Cre8MenuContentTypeInternalLinkPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeInternalLinkPeer::addSelectColumns($criteria);
				$this->collCre8MenuContentTypeInternalLinks = Cre8MenuContentTypeInternalLinkPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Cre8MenuContentTypeInternalLinkPeer::CRE8_MENU_CONTENT_ID, $this->id);

				Cre8MenuContentTypeInternalLinkPeer::addSelectColumns($criteria);
				if (!isset($this->lastCre8MenuContentTypeInternalLinkCriteria) || !$this->lastCre8MenuContentTypeInternalLinkCriteria->equals($criteria)) {
					$this->collCre8MenuContentTypeInternalLinks = Cre8MenuContentTypeInternalLinkPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCre8MenuContentTypeInternalLinkCriteria = $criteria;
		return $this->collCre8MenuContentTypeInternalLinks;
	}

	/**
	 * Returns the number of related Cre8MenuContentTypeInternalLink objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cre8MenuContentTypeInternalLink objects.
	 * @throws     PropelException
	 */
	public function countCre8MenuContentTypeInternalLinks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCre8MenuContentTypeInternalLinks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Cre8MenuContentTypeInternalLinkPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = Cre8MenuContentTypeInternalLinkPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Cre8MenuContentTypeInternalLinkPeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastCre8MenuContentTypeInternalLinkCriteria) || !$this->lastCre8MenuContentTypeInternalLinkCriteria->equals($criteria)) {
					$count = Cre8MenuContentTypeInternalLinkPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCre8MenuContentTypeInternalLinks);
				}
			} else {
				$count = count($this->collCre8MenuContentTypeInternalLinks);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cre8MenuContentTypeInternalLink object to this object
	 * through the Cre8MenuContentTypeInternalLink foreign key attribute.
	 *
	 * @param      Cre8MenuContentTypeInternalLink $l Cre8MenuContentTypeInternalLink
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCre8MenuContentTypeInternalLink(Cre8MenuContentTypeInternalLink $l)
	{
		if ($this->collCre8MenuContentTypeInternalLinks === null) {
			$this->initCre8MenuContentTypeInternalLinks();
		}
		if (!in_array($l, $this->collCre8MenuContentTypeInternalLinks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCre8MenuContentTypeInternalLinks, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collMenuTopBanners collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMenuTopBanners()
	 */
	public function clearMenuTopBanners()
	{
		$this->collMenuTopBanners = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMenuTopBanners collection (array).
	 *
	 * By default this just sets the collMenuTopBanners collection to an empty array (like clearcollMenuTopBanners());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMenuTopBanners()
	{
		$this->collMenuTopBanners = array();
	}

	/**
	 * Gets an array of MenuTopBanner objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related MenuTopBanners from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MenuTopBanner[]
	 * @throws     PropelException
	 */
	public function getMenuTopBanners($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuTopBanners === null) {
			if ($this->isNew()) {
			   $this->collMenuTopBanners = array();
			} else {

				$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuTopBannerPeer::addSelectColumns($criteria);
				$this->collMenuTopBanners = MenuTopBannerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuTopBannerPeer::addSelectColumns($criteria);
				if (!isset($this->lastMenuTopBannerCriteria) || !$this->lastMenuTopBannerCriteria->equals($criteria)) {
					$this->collMenuTopBanners = MenuTopBannerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMenuTopBannerCriteria = $criteria;
		return $this->collMenuTopBanners;
	}

	/**
	 * Returns the number of related MenuTopBanner objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MenuTopBanner objects.
	 * @throws     PropelException
	 */
	public function countMenuTopBanners(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMenuTopBanners === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = MenuTopBannerPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastMenuTopBannerCriteria) || !$this->lastMenuTopBannerCriteria->equals($criteria)) {
					$count = MenuTopBannerPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMenuTopBanners);
				}
			} else {
				$count = count($this->collMenuTopBanners);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MenuTopBanner object to this object
	 * through the MenuTopBanner foreign key attribute.
	 *
	 * @param      MenuTopBanner $l MenuTopBanner
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMenuTopBanner(MenuTopBanner $l)
	{
		if ($this->collMenuTopBanners === null) {
			$this->initMenuTopBanners();
		}
		if (!in_array($l, $this->collMenuTopBanners, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMenuTopBanners, $l);
			$l->setCre8MenuContent($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent is new, it will return
	 * an empty collection; or if this Cre8MenuContent has previously
	 * been saved, it will retrieve related MenuTopBanners from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Cre8MenuContent.
	 */
	public function getMenuTopBannersJoinTopBanner($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuTopBanners === null) {
			if ($this->isNew()) {
				$this->collMenuTopBanners = array();
			} else {

				$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$this->collMenuTopBanners = MenuTopBannerPeer::doSelectJoinTopBanner($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MenuTopBannerPeer::CRE8_MENU_CONTENT_ID, $this->id);

			if (!isset($this->lastMenuTopBannerCriteria) || !$this->lastMenuTopBannerCriteria->equals($criteria)) {
				$this->collMenuTopBanners = MenuTopBannerPeer::doSelectJoinTopBanner($criteria, $con, $join_behavior);
			}
		}
		$this->lastMenuTopBannerCriteria = $criteria;

		return $this->collMenuTopBanners;
	}

	/**
	 * Clears out the collMenuContentTypeCmsWithImages collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMenuContentTypeCmsWithImages()
	 */
	public function clearMenuContentTypeCmsWithImages()
	{
		$this->collMenuContentTypeCmsWithImages = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMenuContentTypeCmsWithImages collection (array).
	 *
	 * By default this just sets the collMenuContentTypeCmsWithImages collection to an empty array (like clearcollMenuContentTypeCmsWithImages());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMenuContentTypeCmsWithImages()
	{
		$this->collMenuContentTypeCmsWithImages = array();
	}

	/**
	 * Gets an array of MenuContentTypeCmsWithImage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related MenuContentTypeCmsWithImages from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MenuContentTypeCmsWithImage[]
	 * @throws     PropelException
	 */
	public function getMenuContentTypeCmsWithImages($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuContentTypeCmsWithImages === null) {
			if ($this->isNew()) {
			   $this->collMenuContentTypeCmsWithImages = array();
			} else {

				$criteria->add(MenuContentTypeCmsWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuContentTypeCmsWithImagePeer::addSelectColumns($criteria);
				$this->collMenuContentTypeCmsWithImages = MenuContentTypeCmsWithImagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MenuContentTypeCmsWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuContentTypeCmsWithImagePeer::addSelectColumns($criteria);
				if (!isset($this->lastMenuContentTypeCmsWithImageCriteria) || !$this->lastMenuContentTypeCmsWithImageCriteria->equals($criteria)) {
					$this->collMenuContentTypeCmsWithImages = MenuContentTypeCmsWithImagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMenuContentTypeCmsWithImageCriteria = $criteria;
		return $this->collMenuContentTypeCmsWithImages;
	}

	/**
	 * Returns the number of related MenuContentTypeCmsWithImage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MenuContentTypeCmsWithImage objects.
	 * @throws     PropelException
	 */
	public function countMenuContentTypeCmsWithImages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMenuContentTypeCmsWithImages === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MenuContentTypeCmsWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = MenuContentTypeCmsWithImagePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MenuContentTypeCmsWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastMenuContentTypeCmsWithImageCriteria) || !$this->lastMenuContentTypeCmsWithImageCriteria->equals($criteria)) {
					$count = MenuContentTypeCmsWithImagePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMenuContentTypeCmsWithImages);
				}
			} else {
				$count = count($this->collMenuContentTypeCmsWithImages);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MenuContentTypeCmsWithImage object to this object
	 * through the MenuContentTypeCmsWithImage foreign key attribute.
	 *
	 * @param      MenuContentTypeCmsWithImage $l MenuContentTypeCmsWithImage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMenuContentTypeCmsWithImage(MenuContentTypeCmsWithImage $l)
	{
		if ($this->collMenuContentTypeCmsWithImages === null) {
			$this->initMenuContentTypeCmsWithImages();
		}
		if (!in_array($l, $this->collMenuContentTypeCmsWithImages, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMenuContentTypeCmsWithImages, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collMenuContentTypeInternalLinkWithImages collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMenuContentTypeInternalLinkWithImages()
	 */
	public function clearMenuContentTypeInternalLinkWithImages()
	{
		$this->collMenuContentTypeInternalLinkWithImages = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMenuContentTypeInternalLinkWithImages collection (array).
	 *
	 * By default this just sets the collMenuContentTypeInternalLinkWithImages collection to an empty array (like clearcollMenuContentTypeInternalLinkWithImages());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMenuContentTypeInternalLinkWithImages()
	{
		$this->collMenuContentTypeInternalLinkWithImages = array();
	}

	/**
	 * Gets an array of MenuContentTypeInternalLinkWithImage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related MenuContentTypeInternalLinkWithImages from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MenuContentTypeInternalLinkWithImage[]
	 * @throws     PropelException
	 */
	public function getMenuContentTypeInternalLinkWithImages($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuContentTypeInternalLinkWithImages === null) {
			if ($this->isNew()) {
			   $this->collMenuContentTypeInternalLinkWithImages = array();
			} else {

				$criteria->add(MenuContentTypeInternalLinkWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuContentTypeInternalLinkWithImagePeer::addSelectColumns($criteria);
				$this->collMenuContentTypeInternalLinkWithImages = MenuContentTypeInternalLinkWithImagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MenuContentTypeInternalLinkWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuContentTypeInternalLinkWithImagePeer::addSelectColumns($criteria);
				if (!isset($this->lastMenuContentTypeInternalLinkWithImageCriteria) || !$this->lastMenuContentTypeInternalLinkWithImageCriteria->equals($criteria)) {
					$this->collMenuContentTypeInternalLinkWithImages = MenuContentTypeInternalLinkWithImagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMenuContentTypeInternalLinkWithImageCriteria = $criteria;
		return $this->collMenuContentTypeInternalLinkWithImages;
	}

	/**
	 * Returns the number of related MenuContentTypeInternalLinkWithImage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MenuContentTypeInternalLinkWithImage objects.
	 * @throws     PropelException
	 */
	public function countMenuContentTypeInternalLinkWithImages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMenuContentTypeInternalLinkWithImages === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MenuContentTypeInternalLinkWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = MenuContentTypeInternalLinkWithImagePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MenuContentTypeInternalLinkWithImagePeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastMenuContentTypeInternalLinkWithImageCriteria) || !$this->lastMenuContentTypeInternalLinkWithImageCriteria->equals($criteria)) {
					$count = MenuContentTypeInternalLinkWithImagePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMenuContentTypeInternalLinkWithImages);
				}
			} else {
				$count = count($this->collMenuContentTypeInternalLinkWithImages);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MenuContentTypeInternalLinkWithImage object to this object
	 * through the MenuContentTypeInternalLinkWithImage foreign key attribute.
	 *
	 * @param      MenuContentTypeInternalLinkWithImage $l MenuContentTypeInternalLinkWithImage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMenuContentTypeInternalLinkWithImage(MenuContentTypeInternalLinkWithImage $l)
	{
		if ($this->collMenuContentTypeInternalLinkWithImages === null) {
			$this->initMenuContentTypeInternalLinkWithImages();
		}
		if (!in_array($l, $this->collMenuContentTypeInternalLinkWithImages, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMenuContentTypeInternalLinkWithImages, $l);
			$l->setCre8MenuContent($this);
		}
	}

	/**
	 * Clears out the collMenuFooterLinkMenus collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMenuFooterLinkMenus()
	 */
	public function clearMenuFooterLinkMenus()
	{
		$this->collMenuFooterLinkMenus = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMenuFooterLinkMenus collection (array).
	 *
	 * By default this just sets the collMenuFooterLinkMenus collection to an empty array (like clearcollMenuFooterLinkMenus());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMenuFooterLinkMenus()
	{
		$this->collMenuFooterLinkMenus = array();
	}

	/**
	 * Gets an array of MenuFooterLinkMenu objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent has previously been saved, it will retrieve
	 * related MenuFooterLinkMenus from storage. If this Cre8MenuContent is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MenuFooterLinkMenu[]
	 * @throws     PropelException
	 */
	public function getMenuFooterLinkMenus($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuFooterLinkMenus === null) {
			if ($this->isNew()) {
			   $this->collMenuFooterLinkMenus = array();
			} else {

				$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuFooterLinkMenuPeer::addSelectColumns($criteria);
				$this->collMenuFooterLinkMenus = MenuFooterLinkMenuPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

				MenuFooterLinkMenuPeer::addSelectColumns($criteria);
				if (!isset($this->lastMenuFooterLinkMenuCriteria) || !$this->lastMenuFooterLinkMenuCriteria->equals($criteria)) {
					$this->collMenuFooterLinkMenus = MenuFooterLinkMenuPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMenuFooterLinkMenuCriteria = $criteria;
		return $this->collMenuFooterLinkMenus;
	}

	/**
	 * Returns the number of related MenuFooterLinkMenu objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MenuFooterLinkMenu objects.
	 * @throws     PropelException
	 */
	public function countMenuFooterLinkMenus(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMenuFooterLinkMenus === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$count = MenuFooterLinkMenuPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

				if (!isset($this->lastMenuFooterLinkMenuCriteria) || !$this->lastMenuFooterLinkMenuCriteria->equals($criteria)) {
					$count = MenuFooterLinkMenuPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMenuFooterLinkMenus);
				}
			} else {
				$count = count($this->collMenuFooterLinkMenus);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MenuFooterLinkMenu object to this object
	 * through the MenuFooterLinkMenu foreign key attribute.
	 *
	 * @param      MenuFooterLinkMenu $l MenuFooterLinkMenu
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMenuFooterLinkMenu(MenuFooterLinkMenu $l)
	{
		if ($this->collMenuFooterLinkMenus === null) {
			$this->initMenuFooterLinkMenus();
		}
		if (!in_array($l, $this->collMenuFooterLinkMenus, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMenuFooterLinkMenus, $l);
			$l->setCre8MenuContent($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Cre8MenuContent is new, it will return
	 * an empty collection; or if this Cre8MenuContent has previously
	 * been saved, it will retrieve related MenuFooterLinkMenus from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Cre8MenuContent.
	 */
	public function getMenuFooterLinkMenusJoinMenuFooterLink($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Cre8MenuContentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuFooterLinkMenus === null) {
			if ($this->isNew()) {
				$this->collMenuFooterLinkMenus = array();
			} else {

				$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

				$this->collMenuFooterLinkMenus = MenuFooterLinkMenuPeer::doSelectJoinMenuFooterLink($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MenuFooterLinkMenuPeer::CRE8_MENU_CONTENT_ID, $this->id);

			if (!isset($this->lastMenuFooterLinkMenuCriteria) || !$this->lastMenuFooterLinkMenuCriteria->equals($criteria)) {
				$this->collMenuFooterLinkMenus = MenuFooterLinkMenuPeer::doSelectJoinMenuFooterLink($criteria, $con, $join_behavior);
			}
		}
		$this->lastMenuFooterLinkMenuCriteria = $criteria;

		return $this->collMenuFooterLinkMenus;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCre8MenuContentTypeFlashs) {
				foreach ((array) $this->collCre8MenuContentTypeFlashs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCre8MenuContentTypeImages) {
				foreach ((array) $this->collCre8MenuContentTypeImages as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCre8MenuContentTypeCmss) {
				foreach ((array) $this->collCre8MenuContentTypeCmss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCre8MenuContentTypeInternalLinks) {
				foreach ((array) $this->collCre8MenuContentTypeInternalLinks as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMenuTopBanners) {
				foreach ((array) $this->collMenuTopBanners as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMenuContentTypeCmsWithImages) {
				foreach ((array) $this->collMenuContentTypeCmsWithImages as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMenuContentTypeInternalLinkWithImages) {
				foreach ((array) $this->collMenuContentTypeInternalLinkWithImages as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMenuFooterLinkMenus) {
				foreach ((array) $this->collMenuFooterLinkMenus as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCre8MenuContentTypeFlashs = null;
		$this->collCre8MenuContentTypeImages = null;
		$this->collCre8MenuContentTypeCmss = null;
		$this->collCre8MenuContentTypeInternalLinks = null;
		$this->collMenuTopBanners = null;
		$this->collMenuContentTypeCmsWithImages = null;
		$this->collMenuContentTypeInternalLinkWithImages = null;
		$this->collMenuFooterLinkMenus = null;
			$this->aCre8MenuType = null;
			$this->aCre8ContentType = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCre8MenuContent:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCre8MenuContent::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCre8MenuContent
